Repository UnknownBugs/TUGUI, pull requests merged in 2021-11, with the labels that each got.

#1 complete adjust of project structure
  Makefile
  README.md
  doc/devDaily/2021_11_dD.md
  libs/MUTILS/defs.h
  libs/MUTILS/icxxabi.hpp
  libs/MUTILS/utils.hpp
  libs/TDEBUG/tdebug.hpp
  platform/base_interface.h
  platform/bootmain.mk
  platform/uefi/Makefile
  platform/uefi/uefi_base_interface_impl.hpp
  platform/uefi/uefi_bootmain.cpp
  platform/uefi/wrapper/gop_wrapper.hpp
  platform/uefi/wrapper/systemtable_wrapper.hpp
  src/colors/color.hpp
  src/tugui.hpp
  test/circle/Makefile
  test/circle/test_circle.cpp
  test/coordinate_line/Makefile
  test/coordinate_line/test_coordinate_line.cpp
  test/rectangle/Makefile
  test/rectangle/test_rectangle.cpp
  test/straight_line/Makefile
  test/straight_line/test_straight_line.cpp
  tools/install_to_disk.sh
Labels: documentation

#5 add math lib
  README.md
  doc/devDaily/2021_11_dD.md
  libs/TMATH/README.md
  libs/TMATH/homocoordinates.hpp
  libs/TMATH/test/test_homocoordinate.cpp
  libs/TMATH/vector.hpp
Labels: documentation, enhancement

#6 change download branch to dev
  README.md
Labels: documentation

#7 add Affine Transform framworks base
  Makefile
  README.md
  core/affinetransform.hpp
  core/tugui.hpp
  doc/devDaily/2021_11_dD.md
  libs/TMATH/formula.hpp
  libs/TMATH/homocoordinates.hpp
  libs/TMATH/test/test_homocoordinate.cpp
  tools/module_name.mk
Labels: documentation, enhancement

#8 add Affine Transform framworks base & fix format
  Makefile
  README.md
  core/affinetransform.hpp
  core/tugui.hpp
  doc/devDaily/2021_11_dD.md
  libs/TMATH/formula.hpp
  libs/TMATH/homocoordinates.hpp
  libs/TMATH/test/test_homocoordinate.cpp
  tools/module_name.mk
Labels: documentation, enhancement

#11 Create makefile.yml
  .github/workflows/makefile.yml
  core/tugui.hpp
Labels: enhancement

#13 add triangle demo
  Makefile
  core/tugui.hpp
  doc/funcDome.md
  doc/images/tugui_triangle.png
  test/triangle/Makefile
  test/triangle/test_triangle.cpp
Labels: enhancement

#15 adjust Makefile structure & platform Interface
  core/tugui.hpp
  libs/MUTILS/defs.hpp
  platform/base_interface.hpp
  platform/uefi/uefi_base_interface_impl.hpp
  platform/uefi/uefi_bootmain.cpp
  test/base/Makefile
  test/circle/Makefile
  test/coordinate_line/Makefile
  test/rectangle/Makefile
  test/straight_line/Makefile
Labels: enhancement

#16 fix drawLine func bug & add test case & add developer guide
  Makefile
  README.md
  core/tugui.hpp
  doc/funcDome.md
  doc/images/test_pic/straight_line_optimize2.png
  doc/images/test_pic/tugui_triangle.png
  libs/MUTILS/utils.hpp
  modules_info.mk
  test/straight_line/test_straight_line.cpp
Labels: documentation, BugFix, AdjustFormat

#22 add Matrix Lib (base)
  libs/TMATH/homocoordinates.hpp
  libs/TMATH/matrix.hpp
  libs/TMATH/test/test_matrix.cpp
  libs/TMATH/test/test_vector.cpp
  libs/TMATH/vector.hpp
Labels: enhancement, design

#28 math: optimize Matrix lib & add demo
  Makefile
  libs/MUTILS/defs.hpp
  libs/TMATH/matrix.hpp
  libs/TMATH/test/test_matrix.cpp
  libs/std/initializer_list.hpp
Labels: enhancement, design

#27 add puts and putc & fix string format
  core/tugui.hpp
  platform/base_interface.hpp
  platform/uefi/uefi_base_interface_impl.hpp
  platform/uefi/wrapper/systemtable_wrapper.hpp
  test/echo-wait/echo-wait.cpp
  test/registerKeyNotify/registerKeyNotify.cpp
  test/timer_sync/timer_sync.cpp
  test/timer_wait/timer_wait.cpp
Labels: enhancement
